# Generated by Django 4.2.2 on 2023-06-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="datetime")),
                (
                    "ext_temp",
                    models.FloatField(default=0.0, verbose_name="T°C Extérieure"),
                ),
                (
                    "house_temp",
                    models.FloatField(default=0.0, verbose_name="T°C Ambiante"),
                ),
                (
                    "house_temp_target",
                    models.FloatField(
                        default=0.0, verbose_name="T°C Ambiante Consigne"
                    ),
                ),
                (
                    "silo_level",
                    models.FloatField(default=0.0, verbose_name="Niveau Sillo kg"),
                ),
                (
                    "hopper_level",
                    models.FloatField(default=0.0, verbose_name="Niveau tremis kg"),
                ),
                (
                    "boiler_water_temp",
                    models.FloatField(default=0.0, verbose_name="T°C Chaudière"),
                ),
                (
                    "boiler_water_temp_target",
                    models.FloatField(
                        default=0.0, verbose_name="T°C Chaudière Consigne"
                    ),
                ),
                (
                    "boiler_modulation",
                    models.FloatField(default=0.0, verbose_name="PE1 Modulation[%]"),
                ),
                (
                    "boiler_fire_temps",
                    models.FloatField(default=0.0, verbose_name="T°C Flamme"),
                ),
                (
                    "boiler_fire_temps_atrget",
                    models.FloatField(default=0.0, verbose_name="T°C Flamme Consigne"),
                ),
                (
                    "heating_start_circulation_temp",
                    models.FloatField(default=0.0, verbose_name="T°C Départ"),
                ),
                (
                    "heating_start_circulation_temp_target",
                    models.FloatField(default=0.0, verbose_name="T°C Départ Consigne"),
                ),
                (
                    "heating_circulation",
                    models.FloatField(
                        default=0.0, verbose_name="Circulateur Chauffage (On/Off)"
                    ),
                ),
                (
                    "heating_status",
                    models.IntegerField(default=0.0, verbose_name="Status Chauff."),
                ),
                ("water_temp", models.FloatField(default=0.0, verbose_name="T°C ECS")),
                (
                    "water_stop_temp",
                    models.FloatField(default=0.0, verbose_name="T°C ECS (arret)"),
                ),
                (
                    "water_temp_target",
                    models.FloatField(default=0.0, verbose_name="T°C ECS Consigne"),
                ),
                (
                    "water_circulation",
                    models.FloatField(default=0.0, verbose_name="Circulateur ECS"),
                ),
                (
                    "water_status",
                    models.IntegerField(default=0, verbose_name="Status ESC"),
                ),
            ],
        ),
    ]
