# Generated by Django 4.2.2 on 2025-10-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okofen_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='datetime',
            field=models.DateTimeField(unique=True, verbose_name='datetime'),
        ),
    ]
