# Generated by Django 4.2.2 on 2025-10-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okofen_data', '0002_alter_rawdata_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('samples_count', models.PositiveIntegerField(default=0)),
                ('boiler_on_seconds', models.FloatField(default=0.0)),
                ('pellet_consumed_kg', models.FloatField(default=0.0)),
                ('ext_temp_mean', models.FloatField(blank=True, null=True)),
                ('ext_temp_night_mean', models.FloatField(blank=True, null=True)),
                ('boiler_water_temp_mean', models.FloatField(blank=True, null=True)),
                ('depart_temp_mean', models.FloatField(blank=True, null=True)),
                ('ambiante_temp_mean', models.FloatField(blank=True, null=True)),
                ('ambiante_temp_night_mean', models.FloatField(blank=True, null=True)),
                ('ecs_temp_heat_mean', models.FloatField(blank=True, null=True)),
                ('ecs_temp_global_mean', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
    ]
